name: Deploy GitHub Pages

on:
  push:
    branches:
      - portfolio  # Tu rama de despliegue

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs  # Carpeta que contiene index.html y todo tu portfolio

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

